### PR TITLE
COMP: Undefined class "QTemporaryFile" when building using SlicerCAT

### PR DESCRIPTION
**Pull request by kerim371**
Without this `#include <QTemporaryFile>` I got compilation error telling me that `QTemporaryFile` is undefined. With this little change I could compile on Windows 10 MSVC2019, Qt 5.15.2

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
The change makes sense. Thank you for your contribution.
