### ISSUE TITLE
Unable to build from source on Apple silicon

### ISSUE THREAD

**Issue by kliron** [Slicer/Slicer#5944]
## Steps to reproduce

I followed all the instructions from the [docs](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/macos.html#prerequisites) to build slicer from source. 

Build halts with the following error while trying to build DCMTK:

```
make[2]: *** [DCMTK-prefix/src/DCMTK-stamp/DCMTK-configure] Error 1
make[1]: *** [CMakeFiles/DCMTK.dir/all] Error 2
-- OpenSSL: Errors detected - See below.

ld: warning: double slash removed from -install_name (/Users/kliron/opt/slicer/OpenSSL//libcrypto.1.1.dylib)
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Users/kliron/opt/slicer/zlib-install/lib/libz.a, building for macOS-i386 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libSystem.tbd (3 slices)

Undefined symbols for architecture i386:

"__DefaultRuneLocale", referenced from:
      _CONF_parse_list in conf_mod.o
  "___bzero", referenced from:
      _ASN1_BIT_STRING_set_bit in a_bitstr.o
      _asn1_item_embed_new in tasn_new.o
      _addr_strings in b_addr.o
      _mem_ctrl in bss_mem.o
      _BLAKE2b_Final in blake2b.o
      _BLAKE2s_Final in blake2s.o
      _bn_div_fixed_top in bn_div.o
      ...

[...an extensive output of a lot more missing symbols...]

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [libcrypto.dylib] Error 1
make[3]: *** [build_libs] Error 2

CMake Error at /Users/kliron/Projects/slicer/CMake/ExternalProjectForNonCMakeProject.cmake:104 (message):
  OpenSSL: build step failed with exit code '2'.
```

## Expected behavior

A successful build.

## Environment
- Slicer version: latest source tree
- Operating system: MacOS Big Sur 11.6

Has anyone been able to compile slicer from source on a M1 Mac? How do I bypass the missing i386 openssl library?

**Comment by brandus1** [comment]
I confirm that the last Slicer version successfully compiles on apple m1 only with OpenSSL built outside of Slicer (configured for darwin x86_64) and SimpleITK disabled.

These relevant flags should be:

`
-DCMAKE_OSX_ARCHITECTURES:STRING=x86_64
-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.1
-DSlicer_USE_SYSTEM_OpenSSL:BOOL=ON 
-DSlicer_USE_SimpleITK:BOOL=OFF
~/Slicer
`

I think the issue is the configuration step of the default slicer openssl build, which allows various dependencies of OpenSSL to be compiled in 32 bit mode, which I believe is not supported in M1 chips. 

In fact, OpenSSL on its own (1.1.1g in this example) builds very nicely with a very simple `./Configure darwin64-x86_64-cc shared`

**Comment by che85** [comment]
Sadly, this doesn't work for me. 

I am trying to compile on macOS Monterey Version 12.2.

OpenSSL (https://github.com/openssl/openssl/tree/OpenSSL_1_1_0-stable) built successfully local.

```
xcode-select version 2392
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
```

I compiled with the following flags:

```
 -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.1 \
 -DQt5_DIR:PATH=~/Qt/5.15.2/clang_64/lib/cmake/Qt5 \
 -DCMAKE_OSX_ARCHITECTURES:STRING=x86_64 \
 -DSlicer_USE_SYSTEM_OpenSSL:BOOL=ON \
 -DSlicer_USE_SimpleITK:BOOL=OFF
```

And getting the following errors:

```
In file included from /Users/herzc/D/S4D/ITK/Modules/Core/Common/include/itkInPlaceImageFilter.h:189:
/Users/herzc/D/S4D/ITK/Modules/Core/Common/include/itkInPlaceImageFilter.hxx:97:5: error: use of undeclared identifier '__ASSERT_FUNCTION'
    itkAssertOrThrowMacro(inputAsOutput.IsNotNull(), "Unable to convert input image to output image as expected!");
    ^
/Users/herzc/D/S4D/ITK/Modules/Core/Common/include/itkMacro.h:754:5: note: expanded from macro 'itkAssertOrThrowMacro'
    itkAssertInDebugOrThrowInReleaseMacro(msgstr.str().c_str());                                                       \
    ^
/Users/herzc/D/S4D/ITK/Modules/Core/Common/include/itkMacro.h:740:95: note: expanded from macro 'itkAssertInDebugOrThrowInReleaseMacro'
#    define itkAssertInDebugOrThrowInReleaseMacro(msg) __assert_fail(msg, __FILE__, __LINE__, __ASSERT_FUNCTION);
                                                                                              ^
```

ITK itself within the Slicer build tree compiles without problems.

**Comment by che85** [comment]
I believe the error appeared when building vtkITKPython so I checked out an older version prior to the Python version being updated and it compiled successfully.

**Comment by brandus1** [comment]
I forgot to mention that I am compiled with `-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.15`, give it a try, I have been using it for a lot now

**Comment by brandus1** [comment]
update: on macOS 12.3 it is also required to use the system LibFFI (I installed the +universal version with macports)
the flag is `-DSlicer_USE_SYSTEM_LibFFI:BOOL=ON`

**Comment by brandus1** [comment]
update: with a universal binary of cmake you can compile easily pretending 'arch -x86_64' to `cmake` and `make`

**Comment by pieper** [comment]
While debugging #6705, I decided to revisit this to see if a native arm64 build would be feasible and it is now possible to do a native build that run with some features disabled.  All the issues look pretty fixable, so we should be able to get working packages with some more effort.

Here's a summary of what I needed to do:

* using Venture 13.0.1 (22A400) on a mac book air M2, Xcode 14.0.1
Build version 14A400
* Installed qt5 and cmake with homebrew
* OpenSSL didn't build by default, so built from source:
```
git clone https://github.com/openssl/openssl.git openssl-git
cd openssl-git
./Configure darwin64-arm64-cc --prefix="/tmp/openssl-arm" no-asm
make && make install
mv OpenSSL-install OpenSSL-install-orig
ln -s /tmp/openssl-arm ./OpenSSL-install
```
* turned off SimpleITK and Slicer_BUILD_DICOM_SUPPORT
* commented out ctypes support in the python checkout:
```
(base) pieper@flake python % git diff
diff --git a/cmake/extensions/CMakeLists.txt b/cmake/extensions/CMakeLists.txt
index a66b833..a4566d8 100644
--- a/cmake/extensions/CMakeLists.txt
+++ b/cmake/extensions/CMakeLists.txt
@@ -382,19 +382,20 @@ if(WIN32)
     endif()
 else()
     if(APPLE)
-        add_python_extension(_ctypes
-            SOURCES ${ctypes_COMMON_SOURCES}
-                    _ctypes/malloc_closure.c
-                    _ctypes/darwin/dlfcn_simple.c
-                    _ctypes/libffi_osx/ffi.c
-                    _ctypes/libffi_osx/x86/darwin64.S
-                    _ctypes/libffi_osx/x86/x86-darwin.S
-                    _ctypes/libffi_osx/x86/x86-ffi_darwin.c
-                    _ctypes/libffi_osx/x86/x86-ffi64.c
-            INCLUDEDIRS ${SRC_DIR}/Modules/_ctypes/libffi_osx/include
-                        ${SRC_DIR}/Modules/_ctypes/darwin
-            DEFINITIONS MACOSX
-        )
+       message("skipping ctypes on mac")
+        #add_python_extension(_ctypes
+            #SOURCES ${ctypes_COMMON_SOURCES}
+                    #_ctypes/malloc_closure.c
+                    #_ctypes/darwin/dlfcn_simple.c
+                    #_ctypes/libffi_osx/ffi.c
+                    #_ctypes/libffi_osx/x86/darwin64.S
+                    #_ctypes/libffi_osx/x86/x86-darwin.S
+                    #_ctypes/libffi_osx/x86/x86-ffi_darwin.c
+                    #_ctypes/libffi_osx/x86/x86-ffi64.c
+            #INCLUDEDIRS ${SRC_DIR}/Modules/_ctypes/libffi_osx/include
+                        #${SRC_DIR}/Modules/_ctypes/darwin
+            #DEFINITIONS MACOSX
+        #)
     else()
         if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
           set(_libffi_system_extra_src
```
* Fix [MultiVolumeExplorer build error](https://github.com/fedorov/MultiVolumeExplorer/pull/51/files)

Unless I forgot something this should be enough to get a working build.

**Comment by lassoan** [comment]
What was the build issue when DICOM support was enabled? DCMTK?

**Comment by jamesobutler** [comment]
Updating DCMTK from 3.6.6 to 3.6.7 will include this bug fix for Apple Silicon https://github.com/DCMTK/dcmtk/commit/5fba853b6f7c13b02bed28bd9f7d3f450e4c72bb
https://github.com/Slicer/Slicer/blob/43b965ecbcf35293087b8c186f8fe75762094ba1/SuperBuild/External_DCMTK.cmake#L55

**Comment by pieper** [comment]
Yes, just DCMTK not supporting the OS version.  I suspect it will work fine with the version @jamesobutler suggests, but I didn't check.  Really the build issues were pretty minor I think that the arm64 build should work fine.  The question is whether/when we want to set up a factory machine and extensions to handle arm64 in addition to x86_64.  It seems both architectures will be in regular use for the next several years.

**Comment by JoshuaKening** [comment]
In the current version of OpenSSL, some errors reported, which indicate that the linker could not find some symbol (function, variable, etc.) when trying to build. This may be due to the link phase can not find the corresponding implementation code caused by. Here are related pictures: 
![image](https://github.com/Slicer/Slicer/assets/129246293/9d17fd26-ced6-46ea-8af1-72862840cc1d)
![image](https://github.com/Slicer/Slicer/assets/129246293/db68d0ef-4e6b-4847-949b-cd58a9e643c8)
Undefined symbols for architecture arm64: 
"_OPENSSL_armcap_P", referenced from: 
... 
"_SHA3_absorb_cext", referenced from: 
... 
ld: symbol(s) not found for architecture arm64 
These errors indicate that the linker could not find the implementation of the symbols _OPENSSL_armcap_P and _SHA3_absorb_cext. This may be due to the lack of the correct library or library path at the time of linking.

**Comment by jamesobutler** [comment]
A macOS build with native arm64 instructions will be needed starting with macOS 28 (expected release fall 2027). Apple has stated that is when most Rosetta 2 functionality will be removed resulting in the ability to no longer run x86_64 built apps. See https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment

**Comment by dstansby** [comment]
I just tried running through the build instructions, and the first one that fails is:
```bash
% mkdir /opt/s
mkdir: /opt/s: Permission denied
```

**Comment by pieper** [comment]
You need to use sudo, like:
```
sudo mkdir /opt/s
sudo chown $USER /opt/s
```
Probably we should add this to the build instructions.

**Comment by dstansby** [comment]
Is there not another directory that typical users have write permissions to that can be used?

**Comment by pieper** [comment]
Not one that's short.  People who develop on macs typically have sudo.  If the path is too long the linker can throw errors.

**Comment by dstansby** [comment]
Okay, I have a build up and running, but running into https://github.com/libffi/libffi/issues/852 - looks like `libffi` needs updating to at least v3.4.7 for the fix (the current version seems to be 3.4.2).

**Comment by pieper** [comment]
It would be great if you could upgrade libffi.  Or you could just try commenting out like I did in the post above.

**Comment by dstansby** [comment]
Updating `libffi` seems to have done the trick with that error. The next one is

```
      ...
  "tbb::detail::r1::terminate(tbb::detail::d1::task_arena_base&)", referenced from:
      tbb::detail::d1::task_arena::terminate() in vtkSMPToolsImpl.cxx.o
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [lib/libvtkCommon-9.5.9.5.dylib] Error 1
make[4]: *** [CMakeFiles/Common.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [VTK-prefix/src/VTK-stamp/VTK-build] Error 2
make[1]: *** [CMakeFiles/VTK.dir/all] Error 2
```

I tried updating VTK to what I think is v9.5.0, but that didn't seem to help.

**Comment by jamesobutler** [comment]
@jcfr, based on https://github.com/Slicer/Slicer/pull/8466#issuecomment-2956110022 - what's the status of the updated libffi branch at https://github.com/python-cmake-buildsystem/libffi/commits/libffi-cmake-buildsystem-v3.4.8-2025-04-10-6a99edb-wip/? Are there cross-platform problems or is it ready for Slicer to use?

**Comment by jamesobutler** [comment]
As of https://github.com/Slicer/Slicer/commit/ec64c5e088f7e5170a3d2b88bf4f492d6efeba63 I know building from source on Apple Silicon is possible for arm64 as well as building x86_64 versions although support for that is already ending with macOS Golden Gate being released this year not able to run on x86_64.
