### PR TITLE
COMP: Fix Windows build errors by explicitly including `Windows.h`

### PR DESCRIPTION
**Pull request by dzenanz**
Explicitly include `Windows.h` in `Base/QTCLI/vtkSlicerCLIModuleLogic.cxx` and 
`Base/QTGUI/qSlicerApplication.cxx` to ensure the availability of Windows-specific 
symbols `MEMORYSTATUSEX` and functions `GetCurrentProcessId()` and `GlobalMemoryStatusEx()`.

----

This fixes a regression introduced in commit 975fa530e49 ("COMP: Remove direct dependency 
on ITK from vtkSlicerApplicationLogic", 2025-01-28), which removed the `itkThreadSupport.h` 
include from `vtkSlicerApplicationLogic.h`. Since `itkThreadSupport.h` indirectly included 
`Windows.h`, its removal caused missing Windows definitions in `qSlicerApplication.cxx` and 
`vtkSlicerCLIModuleLogic.cxx`, leading to the following errors:

- `Base/QTGUI/qSlicerApplication.cxx(1237,3): error C2065: 'MEMORYSTATUSEX': undeclared identifier`
- `Base/QTCLI/vtkSlicerCLIModuleLogic.cxx(469,16): error C3861: 'GetCurrentProcessId': identifier not found`

Including `Windows.h` ensures all required dependencies are correctly included.

> [!NOTE]
> Although `MEMORYSTATUSEX` and `GlobalMemoryStatusEx()` are defined in `sysinfoapi.h`, including only `sysinfoapi.h` results in the following error:
>
> ```
> C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\winnt.h(169,1): 
> error C1189: #error: "No Target Architecture"
> ```

### CODE REVIEW

**Comment by dzenanz** [comment]
Removal of `itkPlatformMultiThreader.h` (which indirectly included `Windows.h`) in 2d30449a58035d7806c8022a4d263970214f1d8b is what probably caused this.

File: Base/QTCLI/vtkSlicerCLIModuleLogic.cxx [hunk 1]
```diff
@@ -56,6 +56,7 @@
 #include <set>
 
 #ifdef _WIN32
+#include <Windows.h>
```
Comment (jcfr) [inline Base/QTCLI/vtkSlicerCLIModuleLogic.cxx:59]:
```suggestion
#include <Windows.h> // for GetCurrentProcessId()
```

File: Base/QTGUI/qSlicerApplication.cxx [hunk 2]
```diff
@@ -35,6 +35,7 @@
 
 #if defined(Q_OS_WIN32)
   #include <QtPlatformHeaders\QWindowsWindowFunctions> // for setHasBorderInFullScreen
+  #include <Windows.h> // for MEMORYSTATUSEX and GlobalMemoryStatusEx
```
Comment (jcfr) [inline Base/QTGUI/qSlicerApplication.cxx:38]:
```suggestion
  #include <Windows.h> // for MEMORYSTATUSEX and GlobalMemoryStatusEx()
```

**Comment by dzenanz** [comment]
Thanks for the amends JC. Looks good.

**Review by jcfr — APPROVED** [review]
