### ISSUE TITLE
Failing to build Slicer VTK with GCC/G++ 11 (numeric_limits not a member of std)

### ISSUE THREAD

**Issue by RafaelPalomar** [Slicer/Slicer#6100]
Building 3D Slicer with gcc/g++-11.2.0 fails on building VTK step with the following errors:

``` txt
[  0%] Building CXX object Common/Core/CMakeFiles/CommonCore-objects.dir/vtkGenericDataArray.cxx.o
In file included from /home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArray.h:72,
                 from /home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArray.cxx:25:
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h: In function ‘bool detail::isnan(T)’:
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: ‘numeric_limits’ is not a member of ‘std’
   52 |   return has_NaN<T, std::numeric_limits<T>::has_quiet_NaN>::isnan(x);
      |                          ^~~~~~~~~~~~~~
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: ‘numeric_limits’ is not a member of ‘std’
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:42: error: template argument 2 is invalid
   52 |   return has_NaN<T, std::numeric_limits<T>::has_quiet_NaN>::isnan(x);
      |                                          ^
In file included from /home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkGenericDataArray.cxx:27:
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkDataArrayPrivate.txx: In function ‘bool vtkDataArrayPrivate::detail::isinf(T)’:
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkDataArrayPrivate.txx:97:31: error: ‘numeric_limits’ is not a member of ‘std’
   97 |   return has_infinity<T, std::numeric_limits<T>::has_infinity>::isinf(x);
      |                               ^~~~~~~~~~~~~~
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkDataArrayPrivate.txx:97:31: error: ‘numeric_limits’ is not a member of ‘std’
/home/rafael/src/Slicer/Slicer/build/VTK/Common/Core/vtkDataArrayPrivate.txx:97:47: error: template argument 2 is invalid
   97 |   return has_infinity<T, std::numeric_limits<T>::has_infinity>::isinf(x);
```

This seems to have been corrected already in VTK (https://gitlab.kitware.com/vtk/vtk/-/issues/18194)

## Steps to reproduce

1.Install gcc/g++ 11.2.0 and set the corresponding variables in Slicer (CMAKE_CXX_COMPILER and CMAKE_C_COMPILER)
2. Build Slicer

## Expected behavior

Slicer should complete the build without errors

## Environment
- Slicer version: Slicer-4.13.0 (ae608a672b49d3fd11efef89f7a2a425f11e11a3)
- Operating system: Gentoo Linux

**Comment by RafaelPalomar** [comment]
Slicer/vtk@baf58b886625d4696b5b60b494905d8b7b423f8a (slicer-v9.1.20211022-1172cdd2e) includes the patch that solves the issue. @jcfr  is Slicer VTK expected to be bumped to v9.1 anytime soon?

**Comment by jcfr** [comment]
Currently working on updating python to 3.9 (at https://github.com/python-cmake-buildsystem/python-cmake-buildsystem), then will finalize VTK updates. I expect this to be completed on the next two weeks.

**Comment by RafaelPalomar** [comment]
Thank you, @jcfr for the quick reply. I'm currently testing this VTK version with the Python 3.9 PR, which I need to build on cutting-edge Linux distros. Let me know if any help is needed to make this happen.
